version: '3.8'

services:
  shopify_db:
    image: postgres:15
    volumes:
      - shopify-data:/var/lib/postgresql/data
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - '5432:5432'
    command: -p 5432

volumes:
  shopify-data: {}
