version: '3.8'

services:
  shopify_db:
    image: postgres:15
    volumes:
      - shopify-data:/var/lib/postgresql/data
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - '5432:5432'
    command: -p 5432

  shopify_redis:
    image: redis:7
    ports:
      - '6379:6379'

  shopify_api:
    container_name: shopify_api
    build:
      context: .
    ports:
      - '3000:3000'
    depends_on:
      - shopify_db
      - shopify_redis
    environment:
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
    env_file:
      - .env
    volumes:
      - .:/app
    command: sh -c "npx prisma migrate deploy && npm run start:prod"

volumes:
  shopify-data: {}
